# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call(`_Rcpp_practice_timesTwo`, x)
}

f1 <- function(x) {
    .Call(`_Rcpp_practice_f1`, x)
}

f2 <- function(x) {
    .Call(`_Rcpp_practice_f2`, x)
}

f3 <- function(x) {
    .Call(`_Rcpp_practice_f3`, x)
}

f4 <- function(pred, x) {
    .Call(`_Rcpp_practice_f4`, pred, x)
}

f5 <- function(x, y) {
    .Call(`_Rcpp_practice_f5`, x, y)
}

sum3 <- function(x) {
    .Call(`_Rcpp_practice_sum3`, x)
}

sum4 <- function(xs) {
    .Call(`_Rcpp_practice_sum4`, xs)
}

sum5 <- function(x) {
    .Call(`_Rcpp_practice_sum5`, x)
}

findInterval2 <- function(x, breaks) {
    .Call(`_Rcpp_practice_findInterval2`, x, breaks)
}

calc_pvalue_cpp <- function(perm_perfs, test_stat) {
    .Call(`_Rcpp_practice_calc_pvalue_cpp`, perm_perfs, test_stat)
}

rcpp_hello_world <- function() {
    .Call(`_Rcpp_practice_rcpp_hello_world`)
}

